#ddev-generated
hooks:
  post-start:
  # Create a new database called "xhgui"
  - exec: |
      if [[ "$DDEV_DATABASE_FAMILY" == "postgres" ]]; then
        echo "SELECT 'CREATE DATABASE xhgui' WHERE NOT EXISTS (SELECT FROM pg_database WHERE datname = 'xhgui')\gexec" | psql > /dev/null
      else
        mysql -uroot -proot -e "CREATE DATABASE IF NOT EXISTS xhgui; GRANT ALL ON xhgui.* to 'db'@'%';"
      fi
    service: db
  - exec: |
      cat <<-'EOF' > .ddev/xhprof/xhprof_prepend.php
      <?php
      // DDEV's built in xhprof handler breaks our own.
      // We'll temporarily override it here, but return control back later.
      // If you don't want this behavior, comment out the hooks in ".ddev/config.xhgui.yaml".
      $homeDir = getenv('HOME');
      $globalAutoload = $homeDir . '/.composer/vendor/autoload.php';
      if (file_exists($globalAutoload)) {
        require_once $globalAutoload;
        // echo "Global autoloader loaded successfully from: $globalAutoload\n";        
      } else {
        error_log("Global autoloader not found at: $globalAutoload");
      }
      EOF
  - exec: |
      cat <<-'EOF' >> /var/www/html/${DDEV_DOCROOT}/sites/default/settings.ddev.php
      if (file_exists("/mnt/ddev_config/xhgui/collector/xhgui.collector.php")) {
        require_once "/mnt/ddev_config/xhgui/collector/xhgui.collector.php";
      }
      EOF

pre-stop:
  - exec: |
      cat <<-EOF > .ddev/xhprof/xhprof_prepend.php
      <?php
      // #ddev-generated
      // We'll give back control of this file to DDEV. Next time it checks, it will see it has ownership
      // and override this file with the current default.
      // If you don't want this behavior, comment out the hooks in .ddev/config.xhgui.yaml.
      return;
      EOF
