#ddev-generated
services:
  xhgui:
    # https://hub.docker.com/r/xhgui/xhgui/tags
    build:
      dockerfile: Dockerfile
      context: xhgui
    container_name: ddev-${DDEV_SITENAME}-xhgui
    labels:
      com.ddev.site-name: ${DDEV_SITENAME}
      com.ddev.approot: $DDEV_APPROOT
    restart: always
    volumes:
      - ./xhgui/nginx.conf:/etc/nginx/http.d/default.conf:ro
      - ./xhgui/xhgui.config.php:/var/www/xhgui/config/config.php
    environment:
      - VIRTUAL_HOST=$DDEV_HOSTNAME
      - HTTP_EXPOSE=8142:80
      - HTTPS_EXPOSE=8143:80
      - XHGUI_MONGO_HOSTNAME=mongo
      - XHGUI_MONGO_DATABASE=xhprof
    links:
      - mongo
    depends_on:
      - mongo

  web:
    links:
      - xhgui
    depends_on:
      - xhgui

  mongo:
    volumes:
      - ./xhgui-mongo/mongo.init.d:/docker-entrypoint-initdb.d
      - mongo:/data/db
volumes:
  mongo:
