#ddev-generated
services:
  xhgui:
    # https://hub.docker.com/r/xhgui/xhgui/tags
    build:
      dockerfile: Dockerfile
      context: xhgui
    container_name: ddev-${DDEV_SITENAME}-xhgui
    labels:
      com.ddev.site-name: ${DDEV_SITENAME}
      com.ddev.approot: $DDEV_APPROOT
    restart: always
    volumes:
      - ./xhgui/nginx.conf:/etc/nginx/http.d/default.conf:ro
      - ./xhgui/xhgui.config.php:/var/www/xhgui/config/config.php
    environment:
      - VIRTUAL_HOST=$DDEV_HOSTNAME
      - HTTP_EXPOSE=8142:80
      - HTTPS_EXPOSE=8143:80
      - XHGUI_MONGO_HOSTNAME=xhgui-mongo
      - XHGUI_MONGO_DATABASE=xhprof
    links:
      - xhgui-mongo
    depends_on:
      - xhgui-mongo

  web:
    links:
      - xhgui
    depends_on:
      - xhgui

  xhgui-mongo:
    # https://hub.docker.com/r/percona/percona-server-mongodb/tags
    image: percona/percona-server-mongodb:6.0-multi
    container_name: ddev-${DDEV_SITENAME}-xhgui-mongo
    command: --storageEngine=wiredTiger
    restart: always
    labels:
      com.ddev.site-name: ${DDEV_SITENAME}
      com.ddev.approot: $DDEV_APPROOT
    environment:
      - MONGO_INITDB_DATABASE=xhprof
    volumes:
      - ./xhgui-mongo/mongo.init.d:/docker-entrypoint-initdb.d
      - xhgui-mongo:/data/db
    expose:
      - "27017"

volumes:
  xhgui-mongo:
